{
 "title": "Execution",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Percentiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(executor_duration_bucket{op='block_execute_time_s'}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(executor_duration_bucket{op='block_execute_time_s'}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(executor_duration_bucket{op='block_execute_time_s'}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "VM execute block time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(executor_duration_bucket{op='vm_execute_block_time_s'}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(executor_duration_bucket{op='vm_execute_block_time_s'}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(executor_duration_bucket{op='vm_execute_block_time_s'}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Total time to commit blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(executor_duration_bucket{op='blocks_commit_time_s'}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(executor_duration_bucket{op='blocks_commit_time_s'}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(executor_duration_bucket{op='blocks_commit_time_s'}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(executor_duration_bucket{op='storage_save_transactions_time_s'}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(executor_duration_bucket{op='storage_save_transactions_time_s'}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(executor_duration_bucket{op='storage_save_transactions_time_s'}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Save Transaction Request message size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(message_size_bucket{message='storage.SaveTransactionsRequest'}[1m])) by (le, message))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(message_size_bucket{message='storage.SaveTransactionsRequest'}[1m])) by (le, message))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(message_size_bucket{message='storage.SaveTransactionsRequest'}[1m])) by (le, message))",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(executor_duration_sum{op='block_execute_time_s'}[1m]) / irate(executor_duration_count{op='block_execute_time_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "VM execute block time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(executor_duration_sum{op='vm_execute_block_time_s'}[1m]) / irate(executor_duration_count{op='vm_execute_block_time_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(executor_duration_sum{op='blocks_commit_time_s'}[1m]) / irate(executor_duration_count{op='blocks_commit_time_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(executor_duration_sum{op='storage_save_transactions_time_s'}[1m]) / irate(executor_duration_count{op='storage_save_transactions_time_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}