{
 "title": "Mempool",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mempool size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_gauge{op=\"txn.system_ttl_index\"}\n\n",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "insertion result",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mempool{op=~'insert..*'}[1m]), 'status', '$1', 'op', '.*code: (.*?),.*')",
     "legendFormat": "{{peer_id}}: {{status}}"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AC add transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(num_req{method=\"mempool.Mempool.AddTransactionWithValidation\"}[1m])\n\n",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg time for get_block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(duration_sum{method=\"mempool.Mempool.GetBlock\"}[1m])/irate(duration_count{method=\"mempool.Mempool.GetBlock\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg time for commit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(duration_sum{method=\"mempool.Mempool.CommitTransactions\"}[1m])/irate(duration_count{method=\"mempool.Mempool.CommitTransactions\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "consensus.committed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(mempool{op=\"commit_transactions.requested\"}[1m])\n",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "consensus.get_block_returned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(mempool{op=\"get_block.returned\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Shared mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Sync with peers (txns per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(mempool{op=\"smp.sync_with_peers\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Incoming events per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mempool{op=~'smp.event.*'}[1m]), 'event', '$1', 'op', 'smp.event.(.*)')",
     "legendFormat": "{{peer_id}}: {{event}}"
    }
   ]
  },
  {
   "title": "New transactions received per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mempool{op=~'smp.transactions.received.*'}[1m]), 'sender', '$1', 'op', 'smp.transactions.received.(.{8}).*')",
     "legendFormat": "{{peer_id}} <- {{sender}}"
    }
   ]
  },
  {
   "title": "Successful transaction sync per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mempool{op=~'smp.transactions.success.*'}[1m]), 'sender', '$1', 'op', 'smp.transactions.success.(.{8}).*')",
     "legendFormat": "{{peer_id}} <- {{sender}}"
    }
   ]
  }
 ]
}