{
 "title": "Overview",
 "description": "Top level view for Validator nodes + Faucet server",
 "tags": [
  "overview",
  "oncall"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "workspace", "label": "Workspace", "query": "label_values(workspace)" },
   {
    "name": "peer_id",
    "label": "Peer",
    "query": "label_values(node_boot_time_seconds{peer_id=~\"[a-z0-9]{8}\"}, peer_id)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 }, "content": "# Workspace: $workspace" },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_boot_time_seconds{role=\"validator\"})"
    }
   ]
  },
  {
   "title": "Total Accounts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(storage_gauge{op=\"new_state_leaves\"}) - max(storage_gauge{op=\"stale_state_leaves\"})"
    }
   ]
  },
  {
   "title": "Total Stored Txn",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(storage_gauge{op=\"latest_transaction_version\"}) + 1"
    }
   ]
  },
  { "title": "General health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "AC SubmitTransaction Request Rate",
   "type": "graph",
   "description": "Rate of submit_transaction requests accepted by AdmissionControl, per-instance view.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "irate(num_req{method=~\"admission_control.AdmissionControl.SubmitTransaction\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "description": "Rate of block commits by consensus, including empty blocks.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_gauge{op='last_committed_round'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed txns per sec",
   "type": "graph",
   "description": "Rate of transactions commits: can be zero if there are no new transactions.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "txns per sec" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_gauge{op='last_committed_version'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "graph",
   "description": "Average time it takes for a transaction to commit since it's received by Mempool.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(mempool_duration_sum{op='e2e.latency'}[1m])/irate(mempool_duration_count{op='e2e.latency'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Failed txns rate",
   "type": "graph",
   "description": "Among all the transactions of the committed blocks, calculates the percentage of the transactions that failed the execution.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * irate(consensus{op=\"failed_txns_count\"}[1m]) / irate(consensus{op=\"committed_txns_count\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Timeout txns per sec",
   "type": "graph",
   "description": "Count the number of active transactions that timeout in mempool",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "txns / sec" }
   ],
   "targets": [
    {
     "expr": "irate(mempool{op=~\"gc.system_ttl_index.active|gc.expiration_time_index.active\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Faucet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "title": "Instance", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 }, "content": "### Faucet" },
  {
   "title": "revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"faucet\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")\n",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"faucet\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='other_nodes',mode='idle',role='faucet'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',role='faucet'} + node_memory_Cached_bytes{workspace='$workspace',role='faucet'} + node_memory_Buffers_bytes{workspace='$workspace',role='faucet'}) / node_memory_MemTotal_bytes{workspace='$workspace',role='faucet'} * 100) by (role)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='other_nodes',role='faucet',mountpoint='/'} / node_filesystem_size_bytes{job='other_nodes'} * 100) by (role)"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "peer_id" },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 14 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 14 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 17 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 17 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 20 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 20 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 23 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 23 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 26 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 26 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 29 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 29 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 32 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 35 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 35 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 38 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 38 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 38 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 38 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 38 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "peer_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "build_info{peer_id=\"$peer_id\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 41 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 41 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_nodes',mode='idle',peer_id='$peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_nodes',peer_id='$peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_nodes'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{role_type='validator',state='connected',peer_id='$peer_id',role='validator'}"
    }
   ]
  }
 ]
}