{
 "title": "State Sync",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Upstream Peers",
   "type": "graph",
   "description": "Number of peers that are currently active and upstream. They are the set of nodes a node can make sync requests to",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Num upstream peers" }
   ],
   "targets": [
    {
     "expr": "state_sync_gauge{op=\"active_upstream_peers\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Apply Chunk Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(state_sync{op=~'apply_chunk_success.*'}, 'chunk_sender_id', '$1', 'op', 'apply_chunk_success.(.*)')",
     "legendFormat": "{{peer_id}}: {{chunk_sender_id}}"
    }
   ]
  },
  {
   "title": "Apply Chunk Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(state_sync{op=~'apply_chunk_failure.*'}, 'chunk_sender_id', '$1', 'op', 'apply_chunk_failure.(.*)')",
     "legendFormat": "{{peer_id}}: {{chunk_sender_id}}"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Committed Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "version number" }
   ],
   "targets": [
    {
     "expr": "state_sync_gauge{op=\"committed_version\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Sync Progress Duration",
   "type": "graph",
   "description": "How long it took to sync a chunk",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "state_sync_duration_sum{op=\"sync_progress_duration\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Target Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "state_sync_gauge{op=\"target_version\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "state_sync{op=\"timeout\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Transaction Replayed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "state_sync{op=\"state_sync_txns_replayed\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Requests and Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Requests Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(state_sync{op=~'requests_sent.*'}, 'requested_peer_id', '$1', 'op', 'requests_sent.(.*)')",
     "legendFormat": "{{peer_id}} : {{requested_peer_id}}"
    }
   ]
  },
  {
   "title": "Response Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(state_sync{op=~'responses_received.*'}, 'response_sender_id', '$1', 'op', 'responses_received.(.*)')",
     "legendFormat": "{{peer_id}} : {{response_sender_id}}"
    }
   ]
  }
 ]
}