{
 "title": "Storage",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cf_name", "query": "storage_gauge" }
  ]
 },
 "panels": [
  {
   "title": "Latest vs Min Readable (Pruned Till) Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op=\"latest_transaction_version\"}",
     "legendFormat": "{{peer_id}}"
    },
    {
     "expr": "storage_gauge{op=\"pruner.least_readable_state_version\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Number of Accounts vs Internal Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(storage_gauge{op=\"new_state_nodes\"}) - max(storage_gauge{op=\"stale_state_nodes\"})",
     "legendFormat": "accounts"
    },
    {
     "expr": "max(storage_gauge{op=\"new_state_nodes\"}) - max(storage_gauge{op=\"stale_state_nodes\"}) - max(storage_gauge{op=\"new_state_leaves\"}) + max(storage_gauge{op=\"stale_state_leaves\"})",
     "legendFormat": "internal_nodes"
    }
   ]
  },
  {
   "title": "Avg Column Family Size By Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg by(op)(storage_gauge{op=~\"cf_size_bytes_.*\"}), \"cf\", \"$1\", \"op\", \"cf_size_bytes_(.*)\")",
     "legendFormat": "{{cf}}"
    }
   ]
  },
  {
   "title": "Column Family Sizes By Validator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "repeat": "cf_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$cf_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Avg Account Updates per Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(storage_gauge{op=\"new_state_leaves\"}[10m])) / max(rate(storage_gauge{op=\"latest_transaction_version\"}[10m]))",
     "legendFormat": "accounts/txn"
    }
   ]
  },
  {
   "title": "Avg Events Emits per Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(storage_gauge{op=\"events_created\"}[10m])) / max(rate(storage_gauge{op=\"latest_transaction_version\"}[10m]))",
     "legendFormat": "events/txn"
    }
   ]
  },
  {
   "title": "Avg Internal Node Updates per Account Update",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(storage_gauge{op=\"new_state_nodes\"}[10m])) / max(rate(storage_gauge{op=\"new_state_leaves\"}[10m])) - 1",
     "legendFormat": "internal nodes/accounts"
    }
   ]
  },
  {
   "title": "Record size (key + value) by Column Family",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    avg by(op)(rate(schemadb_duration_sum{op=~\"db_put_bytes_.*\"}[10m])) / avg by(op)(rate(schemadb_duration_count{op=~\"db_put_bytes_.*\"}[10m])),\n    \"cf\", \"$1\", \"op\", \"db_put_bytes_(.*)\"\n)",
     "legendFormat": "{{cf}}"
    }
   ]
  }
 ]
}