{
 "title": "System - IO",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Write await time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{role='validator'}[1m]) / irate(node_disk_writes_completed_total{role='validator'}[1m]) * 1000 # w_await_ms",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Read await time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{role='validator'}[1m]) / irate(node_disk_reads_completed_total{role='validator'}[1m]) * 1000 # w_await_ms",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{role='validator'}[1m]) # aqu-sz",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{role='validator'}[1m]) # w_iops",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{role='validator'}[1m]) # w_iops",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Written MBs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{role='validator'}[1m])/1024/1024",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Read MBs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{role='validator'}[1m])/1024/1024",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Write Size (KB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{role='validator'}[1m]) / irate(node_disk_writes_completed_total{role='validator'}[1m]) / 1024 # w_size_KB",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Read Size (KB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{role='validator'}[1m]) / irate(node_disk_reads_completed_total{role='validator'}[1m]) / 1024 # r_size_KB",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}