{
 "title": "System",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Validator Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{role='validator'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "HAproxy Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{role='haproxy'}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{role='faucet'}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Validator CPU Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode='idle',role='validator'}[1m])) by (peer_id) / sum(irate(node_cpu_seconds_total{role='validator'}[1m])) by (peer_id)",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "HAproxy CPU Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode='idle',role='haproxy'}[1m])) by (address) / sum(irate(node_cpu_seconds_total{role='haproxy'}[1m])) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet CPU Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode='idle',role='faucet'}[1m])) by (address) / sum(irate(node_cpu_seconds_total{role='faucet'}[1m])) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Validator Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{role='validator',device='eth0'}[1m]) + irate(node_network_transmit_bytes_total{role='validator',device='eth0'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "HAproxy Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{role='haproxy',device='eth0'}[1m]) + irate(node_network_transmit_bytes_total{role='haproxy',device='eth0'}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{role='faucet',device='eth0'}[1m]) + irate(node_network_transmit_bytes_total{role='faucet',device='eth0'}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Validator Sockets Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{role='validator'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "HAproxy Sockets Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{role='haproxy'}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet Sockets Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{role='faucet'}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Validator IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{role='validator'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "HAproxy IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{role='haproxy'}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{role='faucet'}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Validator IO Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{role='validator'}[1m]) + irate(node_disk_writes_completed_total{role='validator'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "HAproxy IO Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{role='haproxy'}[1m]) + irate(node_disk_writes_completed_total{role='haproxy'}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet IO Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{role='faucet'}[1m]) + irate(node_disk_writes_completed_total{role='faucet'}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Validator Disk Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{role='validator',mountpoint=\"/data\"} / node_filesystem_size_bytes{role='validator',mountpoint=\"/data\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "HAproxy Disk Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{role='haproxy',mountpoint=\"/\"} / node_filesystem_size_bytes{role='haproxy',mountpoint=\"/\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet Disk Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{role='faucet',mountpoint=\"/\"} / node_filesystem_size_bytes{role='faucet',mountpoint=\"/\"}",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}